### ISSUE TITLE
How to get numpy to work?

### ISSUE THREAD

**Issue by mattip** [stefanor/pypy3-snap#1]
Not sure if this is an issue or just my ignorance.
Numpy fails to install to the snap. The libm in the snap environment is missing the correct glibc. 
See the [comments](https://github.com/numpy/numpy/issues/15171#issuecomment-568925247) to numpy/numpy#15171. Here is the reproducer, it fails to import numpy.
```
$curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$snap install --classic pypy3
$pypy3 get-pip.py --user
$pypy3 -mpip install --user cython
$pypy3 -mpip install --user numpy
$pypy3 -c "import numpy"
```

**Comment by stefanor** [comment]
Sorry for not replying sooner.

Not sure what the issue was there, but it seems resolved in 7.3.1 & 7.3.2.

```
snap run pypy3 -m venv venv
venv/bin/python -m pip install numpy
venv/bin/python -c 'import numpy'
```

No errors.
